import Image from 'next/image'
import { GetStaticPaths, GetStaticProps, GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import { Key } from 'react'
import {client} from '../utils/client';
import { GetFriends, GetFriendsQuery, GetFriendsQueryVariables } from '../generated/graphql';
import Head from 'next/head'
import Link from 'next/link'

type Data = {
  friends: Record<string, string>[]
}

const QUERY = 
`query {
  friend {
    name
  }
}`

export const getServerSideProps: GetServerSideProps = async (context) => {

  return client.query<GetFriendsQuery, GetFriendsQueryVariables>(GetFriends).toPromise().then(d => {
    console.log(d);
    let data = d.data ? d.data.friend : [];
    return { 
      props:  
       {
        friends: data
      } 
    }
  }).catch(e => {
    return {
      props: {}
    }
  })

  // try {
  //   const response = await fetch(process.env.NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT as string, {
  //     method: 'POST',
  //     headers: {
  //       'x-hasura-admin-secret': process.env.NEXT_PUBLIC_HASURA_ADMIN_SECRET as string,
  //     },
  //     body: JSON.stringify({
  //       query: 
  //       `query {
  //         friend {
  //           name
  //         }
  //       }`
  //     })
  //   });

  //   const result = await response.json();
  //   const data = await result.data;

  //   console.log(data, 'data');

  //   friends = await data.friend;

  //   console.log(friends); 
  // } catch(error){
  //   console.log(error);
  // }
}

interface Props {
  friends: GetFriendsQuery["friend"]
}

const Home: NextPage<Props> = ({friends}) => {
  return (
    <div>
    <Head>
      <title>BYP</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <article className="prose mb-12">
        <h1 className='font-extrabold text-3xl'>
          Welcome to BYP!
          <br />
          The number one place for backyard pizza with YOUR friends.
        </h1>
        <p>
          If you&apos;re new here, you probably need to{" "}
          <Link href="/login">
            <a className='font-extrabold text-md p-1'>Signup</a>
          </Link>
          <a>or</a>
          <Link href="/login">
            <a className='font-extrabold text-md p-1'>Login</a>
          </Link>
          , or you need to scan a party code to get going!
        </p>
      </article>
      <article className="prose mb-4">
        <h2>Pizza Lovin&apos; Patrons include…</h2>
      </article>
      <div className="grid grid-cols-3 md:grid-cols-6 gap-4">
        {friends.map((friend) => (
          <div
            className="p-2 rounded-sm bg-green-200 aspect-square items-center flex"
            key={friend.id}
          >
            <p className="text-center">{friend.username}</p>
          </div>
        ))}
        <div className="p-2 rounded-sm bg-orange-200 aspect-square items-center flex">
          <p>You?</p>
        </div>
      </div>
    </main>
  </div>
  )
}

export default Home;
